### ISSUE TITLE
Reading SPI Data from Sensor

### ISSUE THREAD

**Issue by jeffsrepoaccount** [frak/php_spi#2]
First off, I love the fact that you're porting SPI support to PHP.

I am working through a [tutorial](http://computers.tutsplus.com/tutorials/build-a-raspberry-pi-moisture-sensor-to-monitor-your-plants--mac-52875) using a Rasberry Pi to take sensor readings from an analog moisture sensor connected to an MCP3008 channel which in turn is connected to my model B rev 2 MOSI / MISO pins.  Instead of using python, I (like you) want to use PHP for taking the readings on the sensor.

I have the extension compiled / installed (showing up in `$ php -i | grep -i sdi`) on the rasberry pi, and I can construct an object using your example and call the transfer method on it.  My problem is that I do not know how to _read_ data from the sensor.

The sensor itself is the [Octopus Soil Moisture Sensor](http://www.elecfreaks.com/store/octopus-soil-moisture-sensor-brick-p-422.html), and I can't really find too much documentation out there about it.  Is the method for reading data from an SPI sensor just missing / incomplete, or do you use the transfer or blockTransfer method on the spi object and read the return value?

**Comment by jeffsrepoaccount** [comment]
Thanks for the reply.  My issue was mostly related to my own misunderstanding of SPI, so closing this issue.  FYI- still using this extension and seems to be working great.

**Comment by frak** [comment]
That is good to hear :o)
