### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by jmcconocha** [frak/php_spi#3]
Any idea on what I missed?

--clip--
TIME START 2016-03-16 21:35:59

PASS Spi::__construct() member function [tests/Spi____construct.phpt] 
FAIL Spi::blockTransfer() member function [tests/Spi__blockTransfer.phpt] 
PASS Spi::getInfo() member function [tests/Spi__getInfo.phpt] 
PASS Spi::setupTimer() member function [tests/Spi__setupTimer.phpt] 
FAIL Spi::transfer() member function [tests/Spi__transfer.phpt] 
FAIL Spi::usecDelay() member function [tests/Spi__usecDelay.phpt] 

TIME END 2016-03-16 21:37:00

TEST RESULT SUMMARY

Exts skipped    :    0
Exts tested     :   43

Number of tests :    6                 6
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    3 ( 50.0%) ( 50.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :    3 ( 50.0%) ( 50.0%)

Time taken      :   61 seconds

FAILED TEST SUMMARY

Spi::blockTransfer() member function [tests/Spi__blockTransfer.phpt]
Spi::transfer() member function [tests/Spi__transfer.phpt]
Spi::usecDelay() member function [tests/Spi__usecDelay.phpt]

--/clip--

**Comment by frak** [comment]
Try running the tests as root, the full suite requires elevated permissions.

**Comment by jmcconocha** [comment]
I am running, 'sudo make test'.

**Comment by frak** [comment]
Then I am afraid that I don't know what else to suggest. I never 
actually got to use this code in anger, and I don't even have a 
Raspberry Pi to test on any more. Sorry.

> jmcconocha <mailto:notifications@github.com>
> 16 March 2016 at 22:14
>
> I am running, 'sudo make test'.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/frak/php_spi/issues/3#issuecomment-197579439>
>
> jmcconocha <mailto:notifications@github.com>
> 16 March 2016 at 21:41
>
> Any idea on what I missed?
>
> --clip--
> TIME START 2016-03-16 21:35:59
>
> PASS Spi::__construct() member function [tests/Spi____construct.phpt]
> FAIL Spi::blockTransfer() member function [tests/Spi__blockTransfer.phpt]
> PASS Spi::getInfo() member function [tests/Spi__getInfo.phpt]
> PASS Spi::setupTimer() member function [tests/Spi__setupTimer.phpt]
> FAIL Spi::transfer() member function [tests/Spi__transfer.phpt]
> FAIL Spi::usecDelay() member function [tests/Spi__usecDelay.phpt]
>
> TIME END 2016-03-16 21:37:00
>
> TEST RESULT SUMMARY
>
> Exts skipped : 0
> Exts tested : 43
>
> Number of tests : 6 6
> Tests skipped : 0 ( 0.0%) --------
> Tests warned : 0 ( 0.0%) ( 0.0%)
> Tests failed : 3 ( 50.0%) ( 50.0%)
> Expected fail : 0 ( 0.0%) ( 0.0%)
> Tests passed : 3 ( 50.0%) ( 50.0%)
>
> Time taken : 61 seconds
>
> FAILED TEST SUMMARY
>
> Spi::blockTransfer() member function [tests/Spi__blockTransfer.phpt]
> Spi::transfer() member function [tests/Spi__transfer.phpt]
> Spi::usecDelay() member function [tests/Spi__usecDelay.phpt]
>
> --/clip--
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/frak/php_spi/issues/3>
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by jmcconocha** [comment]
Ok. Thanks for the reply...
